version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: { db }
      POSTGRES_USER: { user }
      POSTGRES_PASSWORD: { pas }
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/{db}
      SPRING_DATASOURCE_USERNAME: { user }
      SPRING_DATASOURCE_PASSWORD: { pas }
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - app

volumes:
  pgdata:
